---
name: test_cluster_tools
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: 'environment.yml'
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: pip install -e . --no-deps

      - name: Prepare tests
        shell: bash -l {0}
        run: python test/base.py

      - name: Run tests
        shell: bash -l {0}
        run: ./run_all_tests.sh
