name: Build and test cluster_tools

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            # os: [ubuntu-latest, windows-latest, macos-latest]
            os: [ubuntu-latest]
            python-version: [3.7]

    name: Test ${{ matrix.os }} - ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cluster_env
          auto-update-conda: true
          environment-file: .github/workflows/environment.yaml
          python-version: ${{ matrix.python-version }}
          use-mamba: true
          mamba-version: "*"
          auto-activate-base: false
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Install package
        shell: bash -l {0}
        run: pip install -e . --no-deps

      - name: Prepare tests
        shell: bash -l {0}
        run: python test/base.py

      - name: Run tests
        shell: bash -l {0}
        run: python -m unittest discover -s test -v
